# Generated by Django 4.2.8 on 2025-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="total_likes_count",
            field=models.IntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AddField(
            model_name="comment",
            name="total_commentlikes_count",
            field=models.IntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.AlterField(
            model_name="article",
            name="Article_title",
            field=models.CharField(max_length=200, verbose_name="게시글 제목"),
        ),
        migrations.AlterField(
            model_name="article",
            name="movie_title",
            field=models.CharField(max_length=200, verbose_name="영화 제목"),
        ),
    ]
