# Generated by Django 4.2.8 on 2025-01-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0010_article_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="title",
        ),
        migrations.AddField(
            model_name="article",
            name="Article_title",
            field=models.CharField(
                default="Default Title", max_length=200, verbose_name="게시글 제목"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="article_like",
            field=models.ManyToManyField(
                blank=True, related_name="liked_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="movie_title",
            field=models.CharField(
                default="Default Title", max_length=200, verbose_name="영화 제목"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_like",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="writer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
