# Generated by Django 4.2.8 on 2025-01-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_remove_article_title_article_article_title_and_more"),
        ("accounts", "0009_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="article_likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="articles.article"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="comment_likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to="articles.comment"
            ),
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
