# Generated by Django 4.2.8 on 2025-01-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_question",
                    models.CharField(max_length=200, verbose_name="질문"),
                ),
                (
                    "bot_response",
                    models.TextField(blank=True, null=True, verbose_name="챗봇 응답"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="질문한 시간"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("genre", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=100)),
                ("rating", models.FloatField()),
            ],
        ),
    ]
