# Generated by Django 4.2.8 on 2025-01-16 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AI", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movie",
        ),
        migrations.AlterField(
            model_name="ai",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
